#!/usr/bin/env zsh
# DEBUG=true
function trace-time() {
    if [ -n "$TT_START" ]; then
        TT_END=$(date +%s.%N)
        # Subtraction won't read scale variable
        TT_DIFF=$(echo "scale=4; ($TT_END - $TT_START)/1" | bc -l)
        echo -e "------------------------------------------------------------- ${TT_DIFF}\r${TT_MSG} "
        TT_START=""
        TT_MSG=""
    fi

    if [ ! $# -eq 0 ]; then
        TT_START=$(date +%s.%N)
        TT_MSG="$@"
    fi
}


[[ -n "$DEBUG" ]] && trace-time "Initializing dotfiles"
#
DOTFILES_PATH=~/dotfiles
BIN_PATH=${BIN_PATH:-~/bin}
HOSTNAME=robin
#
[[ -n "$DEBUG" ]] && trace-time "Loading aliases.zsh"
source ${DOTFILES_PATH}/zsh/aliases.zsh
[[ "$OSTYPE" == "darwin"* ]] && source ${DOTFILES_PATH}/zsh/aliases-osx.zsh
[[ "$OSTYPE" == "linux"* ]] && source ${DOTFILES_PATH}/zsh/aliases-linux.zsh
#
[[ -n "$DEBUG" ]] && trace-time "Loading functions.zsh"
source ${DOTFILES_PATH}/zsh/functions.zsh
#
[[ -n "$DEBUG" ]] && trace-time "Loading snippets.zsh"
source ${DOTFILES_PATH}/zsh/snippets.zsh

#test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

export ZSH=$HOME/.oh-my-zsh
plugins=(git autojump zsh-syntax-highlighting zsh-autosuggestions)

autoload -Uz compinit
compinit

## plugins export
[[ -s ~/.autojump/etc/profile.d/autojump.sh ]] && . ~/.autojump/etc/profile.d/autojump.sh

[ -s "$HOME/.scm_breeze/scm_breeze.sh" ] && source "$HOME/.scm_breeze/scm_breeze.sh"

ZSH_THEME="robbyrussell"

export PATH="/usr/local/bin:/usr/local/sbin:$HOME/bin:$PATH"
source $ZSH/oh-my-zsh.sh

